### ISSUE TITLE
Installation and configuration help

### ISSUE THREAD

**Issue by ghost** [pdxjohnny/SimpleHTTPSServer#2]
Hi,

Is there any documentation for this project on how to configure the server?

Thanks

**Comment by johnandersen777** [comment]
https://github.com/pdxjohnny/SimpleHTTPSServer/blob/master/example.py that
or **main**.py however I would encourage you to use the stock
SimpleHTTPServer or better yet Python 3 http.server and then there is a way
to access the server instance through self.applocation.server or something.
I'm not sure that's documented either but the purpose of my server was to
have something which would be nodejs express like and provide the
self.server object so that methods could share state without using a global
in the file. You can use mine but as it was one of my earlier projects it
is definitely not as good as using the built-ins :-)

**Comment by johnandersen777** [comment]
Clarification added in 5ba0490e1c15541287f89abedfdcd2ff70ad1e88
